// Generated by delombok at Fri Jun 19 16:51:08 IST 2026
package com.Eduportalapp.dto;

import java.util.List;

/**
 * Full detail DTO returned when a user clicks "View Details" on a college card.
 * Includes all institute fields + aggregated programme statistics.
 */
public class InstituteDetailDTO {
    // ── Basic Info ─────────────────────────────────────────────────
    private Long id;
    private String instituteName;
    private String address;
    private String stateName;
    private String districtName;
    private String institutionType;
    private String university;
    private String aicteId;
    private String women;
    private String minority;
    // ── Aggregated Statistics (across all programmes) ──────────────
    private int totalIntake;
    private int totalEnrollment;
    private int totalPlacement;
    private double placementPercentage; // (totalPlacement / totalEnrollment) * 100
    // ── Programme List ─────────────────────────────────────────────
    private List<ProgrammeDTO> programmes;

    // ── Nested DTO ─────────────────────────────────────────────────
    public static class ProgrammeDTO {
        private Long id;
        private String programme;
        private String course;
        private String courseType;
        private String level;
        private String shift;
        private String intake;
        private String availability;
        private String enrollment;
        private String placement;

        @java.lang.SuppressWarnings("all")
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        public String getProgramme() {
            return this.programme;
        }

        @java.lang.SuppressWarnings("all")
        public String getCourse() {
            return this.course;
        }

        @java.lang.SuppressWarnings("all")
        public String getCourseType() {
            return this.courseType;
        }

        @java.lang.SuppressWarnings("all")
        public String getLevel() {
            return this.level;
        }

        @java.lang.SuppressWarnings("all")
        public String getShift() {
            return this.shift;
        }

        @java.lang.SuppressWarnings("all")
        public String getIntake() {
            return this.intake;
        }

        @java.lang.SuppressWarnings("all")
        public String getAvailability() {
            return this.availability;
        }

        @java.lang.SuppressWarnings("all")
        public String getEnrollment() {
            return this.enrollment;
        }

        @java.lang.SuppressWarnings("all")
        public String getPlacement() {
            return this.placement;
        }

        @java.lang.SuppressWarnings("all")
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        public void setProgramme(final String programme) {
            this.programme = programme;
        }

        @java.lang.SuppressWarnings("all")
        public void setCourse(final String course) {
            this.course = course;
        }

        @java.lang.SuppressWarnings("all")
        public void setCourseType(final String courseType) {
            this.courseType = courseType;
        }

        @java.lang.SuppressWarnings("all")
        public void setLevel(final String level) {
            this.level = level;
        }

        @java.lang.SuppressWarnings("all")
        public void setShift(final String shift) {
            this.shift = shift;
        }

        @java.lang.SuppressWarnings("all")
        public void setIntake(final String intake) {
            this.intake = intake;
        }

        @java.lang.SuppressWarnings("all")
        public void setAvailability(final String availability) {
            this.availability = availability;
        }

        @java.lang.SuppressWarnings("all")
        public void setEnrollment(final String enrollment) {
            this.enrollment = enrollment;
        }

        @java.lang.SuppressWarnings("all")
        public void setPlacement(final String placement) {
            this.placement = placement;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof InstituteDetailDTO.ProgrammeDTO)) return false;
            final InstituteDetailDTO.ProgrammeDTO other = (InstituteDetailDTO.ProgrammeDTO) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$programme = this.getProgramme();
            final java.lang.Object other$programme = other.getProgramme();
            if (this$programme == null ? other$programme != null : !this$programme.equals(other$programme)) return false;
            final java.lang.Object this$course = this.getCourse();
            final java.lang.Object other$course = other.getCourse();
            if (this$course == null ? other$course != null : !this$course.equals(other$course)) return false;
            final java.lang.Object this$courseType = this.getCourseType();
            final java.lang.Object other$courseType = other.getCourseType();
            if (this$courseType == null ? other$courseType != null : !this$courseType.equals(other$courseType)) return false;
            final java.lang.Object this$level = this.getLevel();
            final java.lang.Object other$level = other.getLevel();
            if (this$level == null ? other$level != null : !this$level.equals(other$level)) return false;
            final java.lang.Object this$shift = this.getShift();
            final java.lang.Object other$shift = other.getShift();
            if (this$shift == null ? other$shift != null : !this$shift.equals(other$shift)) return false;
            final java.lang.Object this$intake = this.getIntake();
            final java.lang.Object other$intake = other.getIntake();
            if (this$intake == null ? other$intake != null : !this$intake.equals(other$intake)) return false;
            final java.lang.Object this$availability = this.getAvailability();
            final java.lang.Object other$availability = other.getAvailability();
            if (this$availability == null ? other$availability != null : !this$availability.equals(other$availability)) return false;
            final java.lang.Object this$enrollment = this.getEnrollment();
            final java.lang.Object other$enrollment = other.getEnrollment();
            if (this$enrollment == null ? other$enrollment != null : !this$enrollment.equals(other$enrollment)) return false;
            final java.lang.Object this$placement = this.getPlacement();
            final java.lang.Object other$placement = other.getPlacement();
            if (this$placement == null ? other$placement != null : !this$placement.equals(other$placement)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof InstituteDetailDTO.ProgrammeDTO;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $programme = this.getProgramme();
            result = result * PRIME + ($programme == null ? 43 : $programme.hashCode());
            final java.lang.Object $course = this.getCourse();
            result = result * PRIME + ($course == null ? 43 : $course.hashCode());
            final java.lang.Object $courseType = this.getCourseType();
            result = result * PRIME + ($courseType == null ? 43 : $courseType.hashCode());
            final java.lang.Object $level = this.getLevel();
            result = result * PRIME + ($level == null ? 43 : $level.hashCode());
            final java.lang.Object $shift = this.getShift();
            result = result * PRIME + ($shift == null ? 43 : $shift.hashCode());
            final java.lang.Object $intake = this.getIntake();
            result = result * PRIME + ($intake == null ? 43 : $intake.hashCode());
            final java.lang.Object $availability = this.getAvailability();
            result = result * PRIME + ($availability == null ? 43 : $availability.hashCode());
            final java.lang.Object $enrollment = this.getEnrollment();
            result = result * PRIME + ($enrollment == null ? 43 : $enrollment.hashCode());
            final java.lang.Object $placement = this.getPlacement();
            result = result * PRIME + ($placement == null ? 43 : $placement.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "InstituteDetailDTO.ProgrammeDTO(id=" + this.getId() + ", programme=" + this.getProgramme() + ", course=" + this.getCourse() + ", courseType=" + this.getCourseType() + ", level=" + this.getLevel() + ", shift=" + this.getShift() + ", intake=" + this.getIntake() + ", availability=" + this.getAvailability() + ", enrollment=" + this.getEnrollment() + ", placement=" + this.getPlacement() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ProgrammeDTO() {
        }

        @java.lang.SuppressWarnings("all")
        public ProgrammeDTO(final Long id, final String programme, final String course, final String courseType, final String level, final String shift, final String intake, final String availability, final String enrollment, final String placement) {
            this.id = id;
            this.programme = programme;
            this.course = course;
            this.courseType = courseType;
            this.level = level;
            this.shift = shift;
            this.intake = intake;
            this.availability = availability;
            this.enrollment = enrollment;
            this.placement = placement;
        }
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstituteName() {
        return this.instituteName;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getStateName() {
        return this.stateName;
    }

    @java.lang.SuppressWarnings("all")
    public String getDistrictName() {
        return this.districtName;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstitutionType() {
        return this.institutionType;
    }

    @java.lang.SuppressWarnings("all")
    public String getUniversity() {
        return this.university;
    }

    @java.lang.SuppressWarnings("all")
    public String getAicteId() {
        return this.aicteId;
    }

    @java.lang.SuppressWarnings("all")
    public String getWomen() {
        return this.women;
    }

    @java.lang.SuppressWarnings("all")
    public String getMinority() {
        return this.minority;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalIntake() {
        return this.totalIntake;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalEnrollment() {
        return this.totalEnrollment;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalPlacement() {
        return this.totalPlacement;
    }

    @java.lang.SuppressWarnings("all")
    public double getPlacementPercentage() {
        return this.placementPercentage;
    }

    @java.lang.SuppressWarnings("all")
    public List<ProgrammeDTO> getProgrammes() {
        return this.programmes;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstituteName(final String instituteName) {
        this.instituteName = instituteName;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setStateName(final String stateName) {
        this.stateName = stateName;
    }

    @java.lang.SuppressWarnings("all")
    public void setDistrictName(final String districtName) {
        this.districtName = districtName;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitutionType(final String institutionType) {
        this.institutionType = institutionType;
    }

    @java.lang.SuppressWarnings("all")
    public void setUniversity(final String university) {
        this.university = university;
    }

    @java.lang.SuppressWarnings("all")
    public void setAicteId(final String aicteId) {
        this.aicteId = aicteId;
    }

    @java.lang.SuppressWarnings("all")
    public void setWomen(final String women) {
        this.women = women;
    }

    @java.lang.SuppressWarnings("all")
    public void setMinority(final String minority) {
        this.minority = minority;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalIntake(final int totalIntake) {
        this.totalIntake = totalIntake;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalEnrollment(final int totalEnrollment) {
        this.totalEnrollment = totalEnrollment;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalPlacement(final int totalPlacement) {
        this.totalPlacement = totalPlacement;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlacementPercentage(final double placementPercentage) {
        this.placementPercentage = placementPercentage;
    }

    @java.lang.SuppressWarnings("all")
    public void setProgrammes(final List<ProgrammeDTO> programmes) {
        this.programmes = programmes;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof InstituteDetailDTO)) return false;
        final InstituteDetailDTO other = (InstituteDetailDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalIntake() != other.getTotalIntake()) return false;
        if (this.getTotalEnrollment() != other.getTotalEnrollment()) return false;
        if (this.getTotalPlacement() != other.getTotalPlacement()) return false;
        if (java.lang.Double.compare(this.getPlacementPercentage(), other.getPlacementPercentage()) != 0) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$instituteName = this.getInstituteName();
        final java.lang.Object other$instituteName = other.getInstituteName();
        if (this$instituteName == null ? other$instituteName != null : !this$instituteName.equals(other$instituteName)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$stateName = this.getStateName();
        final java.lang.Object other$stateName = other.getStateName();
        if (this$stateName == null ? other$stateName != null : !this$stateName.equals(other$stateName)) return false;
        final java.lang.Object this$districtName = this.getDistrictName();
        final java.lang.Object other$districtName = other.getDistrictName();
        if (this$districtName == null ? other$districtName != null : !this$districtName.equals(other$districtName)) return false;
        final java.lang.Object this$institutionType = this.getInstitutionType();
        final java.lang.Object other$institutionType = other.getInstitutionType();
        if (this$institutionType == null ? other$institutionType != null : !this$institutionType.equals(other$institutionType)) return false;
        final java.lang.Object this$university = this.getUniversity();
        final java.lang.Object other$university = other.getUniversity();
        if (this$university == null ? other$university != null : !this$university.equals(other$university)) return false;
        final java.lang.Object this$aicteId = this.getAicteId();
        final java.lang.Object other$aicteId = other.getAicteId();
        if (this$aicteId == null ? other$aicteId != null : !this$aicteId.equals(other$aicteId)) return false;
        final java.lang.Object this$women = this.getWomen();
        final java.lang.Object other$women = other.getWomen();
        if (this$women == null ? other$women != null : !this$women.equals(other$women)) return false;
        final java.lang.Object this$minority = this.getMinority();
        final java.lang.Object other$minority = other.getMinority();
        if (this$minority == null ? other$minority != null : !this$minority.equals(other$minority)) return false;
        final java.lang.Object this$programmes = this.getProgrammes();
        final java.lang.Object other$programmes = other.getProgrammes();
        if (this$programmes == null ? other$programmes != null : !this$programmes.equals(other$programmes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof InstituteDetailDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getTotalIntake();
        result = result * PRIME + this.getTotalEnrollment();
        result = result * PRIME + this.getTotalPlacement();
        final long $placementPercentage = java.lang.Double.doubleToLongBits(this.getPlacementPercentage());
        result = result * PRIME + (int) ($placementPercentage >>> 32 ^ $placementPercentage);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $instituteName = this.getInstituteName();
        result = result * PRIME + ($instituteName == null ? 43 : $instituteName.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $stateName = this.getStateName();
        result = result * PRIME + ($stateName == null ? 43 : $stateName.hashCode());
        final java.lang.Object $districtName = this.getDistrictName();
        result = result * PRIME + ($districtName == null ? 43 : $districtName.hashCode());
        final java.lang.Object $institutionType = this.getInstitutionType();
        result = result * PRIME + ($institutionType == null ? 43 : $institutionType.hashCode());
        final java.lang.Object $university = this.getUniversity();
        result = result * PRIME + ($university == null ? 43 : $university.hashCode());
        final java.lang.Object $aicteId = this.getAicteId();
        result = result * PRIME + ($aicteId == null ? 43 : $aicteId.hashCode());
        final java.lang.Object $women = this.getWomen();
        result = result * PRIME + ($women == null ? 43 : $women.hashCode());
        final java.lang.Object $minority = this.getMinority();
        result = result * PRIME + ($minority == null ? 43 : $minority.hashCode());
        final java.lang.Object $programmes = this.getProgrammes();
        result = result * PRIME + ($programmes == null ? 43 : $programmes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "InstituteDetailDTO(id=" + this.getId() + ", instituteName=" + this.getInstituteName() + ", address=" + this.getAddress() + ", stateName=" + this.getStateName() + ", districtName=" + this.getDistrictName() + ", institutionType=" + this.getInstitutionType() + ", university=" + this.getUniversity() + ", aicteId=" + this.getAicteId() + ", women=" + this.getWomen() + ", minority=" + this.getMinority() + ", totalIntake=" + this.getTotalIntake() + ", totalEnrollment=" + this.getTotalEnrollment() + ", totalPlacement=" + this.getTotalPlacement() + ", placementPercentage=" + this.getPlacementPercentage() + ", programmes=" + this.getProgrammes() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public InstituteDetailDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public InstituteDetailDTO(final Long id, final String instituteName, final String address, final String stateName, final String districtName, final String institutionType, final String university, final String aicteId, final String women, final String minority, final int totalIntake, final int totalEnrollment, final int totalPlacement, final double placementPercentage, final List<ProgrammeDTO> programmes) {
        this.id = id;
        this.instituteName = instituteName;
        this.address = address;
        this.stateName = stateName;
        this.districtName = districtName;
        this.institutionType = institutionType;
        this.university = university;
        this.aicteId = aicteId;
        this.women = women;
        this.minority = minority;
        this.totalIntake = totalIntake;
        this.totalEnrollment = totalEnrollment;
        this.totalPlacement = totalPlacement;
        this.placementPercentage = placementPercentage;
        this.programmes = programmes;
    }
}
