// Generated by delombok at Fri Jun 19 16:51:08 IST 2026
package com.Eduportalapp.dto;

/**
 * Lightweight projection returned by the paginated college listing endpoint.
 * Only the fields needed to render a college card on the Home page.
 */
public class InstituteCardDTO {
    private Long id;
    private String instituteName;
    private String address;
    private String stateName;
    private String districtName;
    private String institutionType;
    private String university;
    private String aicteId;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstituteName() {
        return this.instituteName;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getStateName() {
        return this.stateName;
    }

    @java.lang.SuppressWarnings("all")
    public String getDistrictName() {
        return this.districtName;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstitutionType() {
        return this.institutionType;
    }

    @java.lang.SuppressWarnings("all")
    public String getUniversity() {
        return this.university;
    }

    @java.lang.SuppressWarnings("all")
    public String getAicteId() {
        return this.aicteId;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstituteName(final String instituteName) {
        this.instituteName = instituteName;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setStateName(final String stateName) {
        this.stateName = stateName;
    }

    @java.lang.SuppressWarnings("all")
    public void setDistrictName(final String districtName) {
        this.districtName = districtName;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitutionType(final String institutionType) {
        this.institutionType = institutionType;
    }

    @java.lang.SuppressWarnings("all")
    public void setUniversity(final String university) {
        this.university = university;
    }

    @java.lang.SuppressWarnings("all")
    public void setAicteId(final String aicteId) {
        this.aicteId = aicteId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof InstituteCardDTO)) return false;
        final InstituteCardDTO other = (InstituteCardDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$instituteName = this.getInstituteName();
        final java.lang.Object other$instituteName = other.getInstituteName();
        if (this$instituteName == null ? other$instituteName != null : !this$instituteName.equals(other$instituteName)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$stateName = this.getStateName();
        final java.lang.Object other$stateName = other.getStateName();
        if (this$stateName == null ? other$stateName != null : !this$stateName.equals(other$stateName)) return false;
        final java.lang.Object this$districtName = this.getDistrictName();
        final java.lang.Object other$districtName = other.getDistrictName();
        if (this$districtName == null ? other$districtName != null : !this$districtName.equals(other$districtName)) return false;
        final java.lang.Object this$institutionType = this.getInstitutionType();
        final java.lang.Object other$institutionType = other.getInstitutionType();
        if (this$institutionType == null ? other$institutionType != null : !this$institutionType.equals(other$institutionType)) return false;
        final java.lang.Object this$university = this.getUniversity();
        final java.lang.Object other$university = other.getUniversity();
        if (this$university == null ? other$university != null : !this$university.equals(other$university)) return false;
        final java.lang.Object this$aicteId = this.getAicteId();
        final java.lang.Object other$aicteId = other.getAicteId();
        if (this$aicteId == null ? other$aicteId != null : !this$aicteId.equals(other$aicteId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof InstituteCardDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $instituteName = this.getInstituteName();
        result = result * PRIME + ($instituteName == null ? 43 : $instituteName.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $stateName = this.getStateName();
        result = result * PRIME + ($stateName == null ? 43 : $stateName.hashCode());
        final java.lang.Object $districtName = this.getDistrictName();
        result = result * PRIME + ($districtName == null ? 43 : $districtName.hashCode());
        final java.lang.Object $institutionType = this.getInstitutionType();
        result = result * PRIME + ($institutionType == null ? 43 : $institutionType.hashCode());
        final java.lang.Object $university = this.getUniversity();
        result = result * PRIME + ($university == null ? 43 : $university.hashCode());
        final java.lang.Object $aicteId = this.getAicteId();
        result = result * PRIME + ($aicteId == null ? 43 : $aicteId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "InstituteCardDTO(id=" + this.getId() + ", instituteName=" + this.getInstituteName() + ", address=" + this.getAddress() + ", stateName=" + this.getStateName() + ", districtName=" + this.getDistrictName() + ", institutionType=" + this.getInstitutionType() + ", university=" + this.getUniversity() + ", aicteId=" + this.getAicteId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public InstituteCardDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public InstituteCardDTO(final Long id, final String instituteName, final String address, final String stateName, final String districtName, final String institutionType, final String university, final String aicteId) {
        this.id = id;
        this.instituteName = instituteName;
        this.address = address;
        this.stateName = stateName;
        this.districtName = districtName;
        this.institutionType = institutionType;
        this.university = university;
        this.aicteId = aicteId;
    }
}
