spring.application.name=Eduportal


spring.datasource.url=${database_URL}
spring.datasource.username=${database_USER}
spring.datasource.password=${database_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver