// Generated by delombok at Fri Jun 19 16:41:45 IST 2026
package com.Eduportalapp.model;

import jakarta.persistence.*;

@Entity
@Table(name = "district")
public class District {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "state_id")
    private Long stateId;
    @Column(name = "district_name")
    private String districtName;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getStateId() {
        return this.stateId;
    }

    @java.lang.SuppressWarnings("all")
    public String getDistrictName() {
        return this.districtName;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setStateId(final Long stateId) {
        this.stateId = stateId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDistrictName(final String districtName) {
        this.districtName = districtName;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof District)) return false;
        final District other = (District) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$stateId = this.getStateId();
        final java.lang.Object other$stateId = other.getStateId();
        if (this$stateId == null ? other$stateId != null : !this$stateId.equals(other$stateId)) return false;
        final java.lang.Object this$districtName = this.getDistrictName();
        final java.lang.Object other$districtName = other.getDistrictName();
        if (this$districtName == null ? other$districtName != null : !this$districtName.equals(other$districtName)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof District;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $stateId = this.getStateId();
        result = result * PRIME + ($stateId == null ? 43 : $stateId.hashCode());
        final java.lang.Object $districtName = this.getDistrictName();
        result = result * PRIME + ($districtName == null ? 43 : $districtName.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "District(id=" + this.getId() + ", stateId=" + this.getStateId() + ", districtName=" + this.getDistrictName() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public District() {
    }

    @java.lang.SuppressWarnings("all")
    public District(final Long id, final Long stateId, final String districtName) {
        this.id = id;
        this.stateId = stateId;
        this.districtName = districtName;
    }
}
