// Generated by delombok at Fri Jun 19 16:41:45 IST 2026
package com.Eduportalapp.model;

import jakarta.persistence.*;

@Entity
@Table(name = "institute")
public class Institute {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "state_id")
    private Long stateId;
    @Column(name = "district_id")
    private Long districtId;
    @Column(name = "address", columnDefinition = "TEXT")
    private String address;
    @Column(name = "institution_type")
    private String institutionType;
    @Column(name = "women")
    private String women;
    @Column(name = "minority")
    private String minority;
    @Column(name = "other_id")
    private String otherId;
    @Column(name = "university")
    private String university;
    @Column(name = "aicte_id")
    private String aicteId;
    @Column(name = "institute_name")
    private String instituteName;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getStateId() {
        return this.stateId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getDistrictId() {
        return this.districtId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstitutionType() {
        return this.institutionType;
    }

    @java.lang.SuppressWarnings("all")
    public String getWomen() {
        return this.women;
    }

    @java.lang.SuppressWarnings("all")
    public String getMinority() {
        return this.minority;
    }

    @java.lang.SuppressWarnings("all")
    public String getOtherId() {
        return this.otherId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUniversity() {
        return this.university;
    }

    @java.lang.SuppressWarnings("all")
    public String getAicteId() {
        return this.aicteId;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstituteName() {
        return this.instituteName;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setStateId(final Long stateId) {
        this.stateId = stateId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDistrictId(final Long districtId) {
        this.districtId = districtId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitutionType(final String institutionType) {
        this.institutionType = institutionType;
    }

    @java.lang.SuppressWarnings("all")
    public void setWomen(final String women) {
        this.women = women;
    }

    @java.lang.SuppressWarnings("all")
    public void setMinority(final String minority) {
        this.minority = minority;
    }

    @java.lang.SuppressWarnings("all")
    public void setOtherId(final String otherId) {
        this.otherId = otherId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUniversity(final String university) {
        this.university = university;
    }

    @java.lang.SuppressWarnings("all")
    public void setAicteId(final String aicteId) {
        this.aicteId = aicteId;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstituteName(final String instituteName) {
        this.instituteName = instituteName;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Institute)) return false;
        final Institute other = (Institute) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$stateId = this.getStateId();
        final java.lang.Object other$stateId = other.getStateId();
        if (this$stateId == null ? other$stateId != null : !this$stateId.equals(other$stateId)) return false;
        final java.lang.Object this$districtId = this.getDistrictId();
        final java.lang.Object other$districtId = other.getDistrictId();
        if (this$districtId == null ? other$districtId != null : !this$districtId.equals(other$districtId)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$institutionType = this.getInstitutionType();
        final java.lang.Object other$institutionType = other.getInstitutionType();
        if (this$institutionType == null ? other$institutionType != null : !this$institutionType.equals(other$institutionType)) return false;
        final java.lang.Object this$women = this.getWomen();
        final java.lang.Object other$women = other.getWomen();
        if (this$women == null ? other$women != null : !this$women.equals(other$women)) return false;
        final java.lang.Object this$minority = this.getMinority();
        final java.lang.Object other$minority = other.getMinority();
        if (this$minority == null ? other$minority != null : !this$minority.equals(other$minority)) return false;
        final java.lang.Object this$otherId = this.getOtherId();
        final java.lang.Object other$otherId = other.getOtherId();
        if (this$otherId == null ? other$otherId != null : !this$otherId.equals(other$otherId)) return false;
        final java.lang.Object this$university = this.getUniversity();
        final java.lang.Object other$university = other.getUniversity();
        if (this$university == null ? other$university != null : !this$university.equals(other$university)) return false;
        final java.lang.Object this$aicteId = this.getAicteId();
        final java.lang.Object other$aicteId = other.getAicteId();
        if (this$aicteId == null ? other$aicteId != null : !this$aicteId.equals(other$aicteId)) return false;
        final java.lang.Object this$instituteName = this.getInstituteName();
        final java.lang.Object other$instituteName = other.getInstituteName();
        if (this$instituteName == null ? other$instituteName != null : !this$instituteName.equals(other$instituteName)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Institute;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $stateId = this.getStateId();
        result = result * PRIME + ($stateId == null ? 43 : $stateId.hashCode());
        final java.lang.Object $districtId = this.getDistrictId();
        result = result * PRIME + ($districtId == null ? 43 : $districtId.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $institutionType = this.getInstitutionType();
        result = result * PRIME + ($institutionType == null ? 43 : $institutionType.hashCode());
        final java.lang.Object $women = this.getWomen();
        result = result * PRIME + ($women == null ? 43 : $women.hashCode());
        final java.lang.Object $minority = this.getMinority();
        result = result * PRIME + ($minority == null ? 43 : $minority.hashCode());
        final java.lang.Object $otherId = this.getOtherId();
        result = result * PRIME + ($otherId == null ? 43 : $otherId.hashCode());
        final java.lang.Object $university = this.getUniversity();
        result = result * PRIME + ($university == null ? 43 : $university.hashCode());
        final java.lang.Object $aicteId = this.getAicteId();
        result = result * PRIME + ($aicteId == null ? 43 : $aicteId.hashCode());
        final java.lang.Object $instituteName = this.getInstituteName();
        result = result * PRIME + ($instituteName == null ? 43 : $instituteName.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Institute(id=" + this.getId() + ", stateId=" + this.getStateId() + ", districtId=" + this.getDistrictId() + ", address=" + this.getAddress() + ", institutionType=" + this.getInstitutionType() + ", women=" + this.getWomen() + ", minority=" + this.getMinority() + ", otherId=" + this.getOtherId() + ", university=" + this.getUniversity() + ", aicteId=" + this.getAicteId() + ", instituteName=" + this.getInstituteName() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Institute() {
    }

    @java.lang.SuppressWarnings("all")
    public Institute(final Long id, final Long stateId, final Long districtId, final String address, final String institutionType, final String women, final String minority, final String otherId, final String university, final String aicteId, final String instituteName) {
        this.id = id;
        this.stateId = stateId;
        this.districtId = districtId;
        this.address = address;
        this.institutionType = institutionType;
        this.women = women;
        this.minority = minority;
        this.otherId = otherId;
        this.university = university;
        this.aicteId = aicteId;
        this.instituteName = instituteName;
    }
}
