// Generated by delombok at Fri Jun 19 16:41:45 IST 2026
package com.Eduportalapp.model;

import jakarta.persistence.*;

@Entity
@Table(name = "programme")
public class Programme {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "institute_id")
    private Long instituteId;
    @Column(name = "programme")
    private String programme;
    @Column(name = "course")
    private String course;
    @Column(name = "course_type")
    private String courseType;
    @Column(name = "level")
    private String level;
    @Column(name = "shift")
    private String shift;
    @Column(name = "intake")
    private String intake;
    @Column(name = "availability")
    private String availability;
    @Column(name = "enrollment")
    private String enrollment;
    @Column(name = "placement")
    private String placement;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getInstituteId() {
        return this.instituteId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProgramme() {
        return this.programme;
    }

    @java.lang.SuppressWarnings("all")
    public String getCourse() {
        return this.course;
    }

    @java.lang.SuppressWarnings("all")
    public String getCourseType() {
        return this.courseType;
    }

    @java.lang.SuppressWarnings("all")
    public String getLevel() {
        return this.level;
    }

    @java.lang.SuppressWarnings("all")
    public String getShift() {
        return this.shift;
    }

    @java.lang.SuppressWarnings("all")
    public String getIntake() {
        return this.intake;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvailability() {
        return this.availability;
    }

    @java.lang.SuppressWarnings("all")
    public String getEnrollment() {
        return this.enrollment;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlacement() {
        return this.placement;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstituteId(final Long instituteId) {
        this.instituteId = instituteId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProgramme(final String programme) {
        this.programme = programme;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourse(final String course) {
        this.course = course;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseType(final String courseType) {
        this.courseType = courseType;
    }

    @java.lang.SuppressWarnings("all")
    public void setLevel(final String level) {
        this.level = level;
    }

    @java.lang.SuppressWarnings("all")
    public void setShift(final String shift) {
        this.shift = shift;
    }

    @java.lang.SuppressWarnings("all")
    public void setIntake(final String intake) {
        this.intake = intake;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvailability(final String availability) {
        this.availability = availability;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnrollment(final String enrollment) {
        this.enrollment = enrollment;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlacement(final String placement) {
        this.placement = placement;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Programme)) return false;
        final Programme other = (Programme) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$instituteId = this.getInstituteId();
        final java.lang.Object other$instituteId = other.getInstituteId();
        if (this$instituteId == null ? other$instituteId != null : !this$instituteId.equals(other$instituteId)) return false;
        final java.lang.Object this$programme = this.getProgramme();
        final java.lang.Object other$programme = other.getProgramme();
        if (this$programme == null ? other$programme != null : !this$programme.equals(other$programme)) return false;
        final java.lang.Object this$course = this.getCourse();
        final java.lang.Object other$course = other.getCourse();
        if (this$course == null ? other$course != null : !this$course.equals(other$course)) return false;
        final java.lang.Object this$courseType = this.getCourseType();
        final java.lang.Object other$courseType = other.getCourseType();
        if (this$courseType == null ? other$courseType != null : !this$courseType.equals(other$courseType)) return false;
        final java.lang.Object this$level = this.getLevel();
        final java.lang.Object other$level = other.getLevel();
        if (this$level == null ? other$level != null : !this$level.equals(other$level)) return false;
        final java.lang.Object this$shift = this.getShift();
        final java.lang.Object other$shift = other.getShift();
        if (this$shift == null ? other$shift != null : !this$shift.equals(other$shift)) return false;
        final java.lang.Object this$intake = this.getIntake();
        final java.lang.Object other$intake = other.getIntake();
        if (this$intake == null ? other$intake != null : !this$intake.equals(other$intake)) return false;
        final java.lang.Object this$availability = this.getAvailability();
        final java.lang.Object other$availability = other.getAvailability();
        if (this$availability == null ? other$availability != null : !this$availability.equals(other$availability)) return false;
        final java.lang.Object this$enrollment = this.getEnrollment();
        final java.lang.Object other$enrollment = other.getEnrollment();
        if (this$enrollment == null ? other$enrollment != null : !this$enrollment.equals(other$enrollment)) return false;
        final java.lang.Object this$placement = this.getPlacement();
        final java.lang.Object other$placement = other.getPlacement();
        if (this$placement == null ? other$placement != null : !this$placement.equals(other$placement)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Programme;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $instituteId = this.getInstituteId();
        result = result * PRIME + ($instituteId == null ? 43 : $instituteId.hashCode());
        final java.lang.Object $programme = this.getProgramme();
        result = result * PRIME + ($programme == null ? 43 : $programme.hashCode());
        final java.lang.Object $course = this.getCourse();
        result = result * PRIME + ($course == null ? 43 : $course.hashCode());
        final java.lang.Object $courseType = this.getCourseType();
        result = result * PRIME + ($courseType == null ? 43 : $courseType.hashCode());
        final java.lang.Object $level = this.getLevel();
        result = result * PRIME + ($level == null ? 43 : $level.hashCode());
        final java.lang.Object $shift = this.getShift();
        result = result * PRIME + ($shift == null ? 43 : $shift.hashCode());
        final java.lang.Object $intake = this.getIntake();
        result = result * PRIME + ($intake == null ? 43 : $intake.hashCode());
        final java.lang.Object $availability = this.getAvailability();
        result = result * PRIME + ($availability == null ? 43 : $availability.hashCode());
        final java.lang.Object $enrollment = this.getEnrollment();
        result = result * PRIME + ($enrollment == null ? 43 : $enrollment.hashCode());
        final java.lang.Object $placement = this.getPlacement();
        result = result * PRIME + ($placement == null ? 43 : $placement.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Programme(id=" + this.getId() + ", instituteId=" + this.getInstituteId() + ", programme=" + this.getProgramme() + ", course=" + this.getCourse() + ", courseType=" + this.getCourseType() + ", level=" + this.getLevel() + ", shift=" + this.getShift() + ", intake=" + this.getIntake() + ", availability=" + this.getAvailability() + ", enrollment=" + this.getEnrollment() + ", placement=" + this.getPlacement() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Programme() {
    }

    @java.lang.SuppressWarnings("all")
    public Programme(final Long id, final Long instituteId, final String programme, final String course, final String courseType, final String level, final String shift, final String intake, final String availability, final String enrollment, final String placement) {
        this.id = id;
        this.instituteId = instituteId;
        this.programme = programme;
        this.course = course;
        this.courseType = courseType;
        this.level = level;
        this.shift = shift;
        this.intake = intake;
        this.availability = availability;
        this.enrollment = enrollment;
        this.placement = placement;
    }
}
